[package]
name = "test"
version = "1.0.0"
authors = []

[addresses]
test = "_"

[dev-addresses]
test = "0x123"

[dependencies]
aptos_packages = { git = "git@github.com:SnowFishLabs/aptos_packages.git", rev = "master" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }

[dev-dependencies]
aptos_packages = { local = "deps/aptos_packages" }