name: Deploy Move packages to github packages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  pull_request:
    branches: [ master ]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: https://npm.pkg.github.com/
      - name: Setup SSH
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/ssh.key
          chmod 600 $HOME/.ssh/ssh.key
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone git@github.com:SnowFishLabs/aptos_packages.git
      - name: Setup Aptos CLI
        uses: WGB5445/aptos-cli-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "7.5.0"
      - name: Build Move Packages
        run: aptos move build --included-artifacts none --save-metadata --named-addresses test=0x11075e54838a4f97e5af4141b08c0e0bccb7b1d57b36757bc62539ee97342008
      - name: Publish Move Packages
        run: node ghscripts/publish.js
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
