name: Deploy Move packages to github packages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  pull_request:
    branches: [ master ]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: https://npm.pkg.github.com/
      - name: Setup Aptos CLI
        uses: WGB5445/aptos-cli-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "7.5.0"
      - name: Build Move Packages
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/ssh.key
          chmod 600 $HOME/.ssh/ssh.key
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          aptos move build --included-artifacts none --save-metadata --named-addresses test=0x11075e54838a4f97e5af4141b08c0e0bccb7b1d57b36757bc62539ee97342008
      - name: Setup Move Packages
        uses: fantasyni/setup_move@v1
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # - name: Publish Move Packages
      #   run: node .github/workflows/publish.js
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #     GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Setup Notification
        uses: fantasyni/setup_notification@v1
        with:
          user-id: "lark-test"
          api-key: ${{secrets.NOTIFICATION_API_KEY}}
          run-id: ${{ github.run_id }}
          content: "成功"
      - name: failure Notification
        if: ${{ failure() }}
        uses: fantasyni/setup_notification@v1
        with:
          user-id: "lark-test"
          api-key: ${{secrets.NOTIFICATION_API_KEY}}
          run-id: ${{ github.run_id }}
          content: "失败"